package com.privateinvest.aitraderpro.navigation

sealed class AppDestination(val route: String, val label: String) {
    data object Login : AppDestination("login", "Connexion")
    data object Dashboard : AppDestination("dashboard", "Accueil")
    data object TopOpportunities : AppDestination("top_opportunities", "Opportunités")
    data object Watchlist : AppDestination("watchlist", "Watchlist")
    data object Alerts : AppDestination("alerts", "Alertes")
    data object Portfolio : AppDestination("portfolio", "Portefeuille")
    data object Audit : AppDestination("audit", "Audit IA")
    data object Admin : AppDestination("admin", "Paramètres")
    data object Risk : AppDestination("risk", "Risque")
    data object AssetDetail : AppDestination("asset_detail", "Actif")
    data object SignalAssistant : AppDestination("signal_assistant", "Pourquoi ce signal ?")
    data object More : AppDestination("more", "Plus")
    data object InstallTest : AppDestination("install_test", "Test complet")
    data object JournalIA : AppDestination("journal_ia", "Journal IA")
    data object CalendarIA : AppDestination("calendar_ia", "Calendrier IA")
    data object Favorites : AppDestination("favorites", "Favoris")
    data object Health : AppDestination("health", "Santé IA")
    data object Goals : AppDestination("goals", "Objectifs")
    data object Backup : AppDestination("backup", "Sauvegarde")
    data object Exports : AppDestination("exports", "Exports")
    data object BrokerAssistant : AppDestination("broker_assistant", "Assistant investissement")
    data object SecurityCenter : AppDestination("security_center", "Sécurité")
    data object StatsCenter : AppDestination("stats_center", "Statistiques")
    data object PreferencesCenter : AppDestination("preferences_center", "Préférences")
    data object MultiPortfolio : AppDestination("multi_portfolio", "Portefeuilles")
    data object DailyReport : AppDestination("daily_report", "Rapport quotidien")
    data object Onboarding : AppDestination("onboarding", "Première utilisation")
    data object StrategyMonitoring : AppDestination("strategy_monitoring", "Suivi intelligent")
    data object AiForecasts : AppDestination("ai_forecasts", "Pronostics IA")
    data object MarketDataCenter : AppDestination("market_data_center", "Données marché")
    // V1.4 : Centre de Contrôle Intelligent + Validation Réelle
    data object ControlCenter : AppDestination("control_center", "Cockpit IA")
    data object RealValidation : AppDestination("real_validation", "Validation Réelle")
}
